spring:
  application:
  name: EurekaServer
  
server:
  port: 8761
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
  service-url:
    defaultZone: http://localhost:8761/eureka
    
spring:
  cloud:
   config:
   server:
   git:
   uri: https://github.com/leonavevor/scf-config-repository.git
       
    
 
spring:
  cloud:
   config:
    encrypt:
      enabled: false